Fixed reading timestamps from poco with QueryValues
influxdata/influxdb-client-csharp pull request #120
Opened 2020-09-01 19:41 UTC by ritchiecarroll

Closes ##119

This fixes issue with reading timestamps for a poco object when using QueryAsync<T>

Also caches reflection on poco to optimize deserialization.

2020-09-08 09:12 UTC, bednar requested changes
Hi @ritchiecarroll,

thanks for your PR, there is a small glitch in your implementation, but is an awesome improvement! 

Could you please fix review requirements and also update a `CHANGELOG.md` file?

Regards

2020-09-08 09:12 UTC, bednar commented on Client.Core/Flux/Internal/FluxResultMapper.cs
> +                        SetFieldValue(poco, property, record.GetTimeInDateTime());
We should also support a timestamp field with the `Instant` type. The POCO could looks like:

```csharp
private class PointWithoutTimestampNameInstant
{
    [Column("tag", IsTag = true)] public string Tag { get; set; }
    [Column("min")] public double Minimum { get; set; }
    [Column("max")] public double Maximum { get; set; }
    [Column("avg")] public Double Average { get; set; }
    [Column(IsTimestamp = true)] public Instant Timestamp { get; set; }
}
```

Could you please add a following test into `FluxResultMapperTest.cs`:

```csharp
[Test]
public void MapTimestampWithInstantTime()
{
    var now = DateTime.UtcNow;
    
    var fluxRecord = new FluxRecord(0);
    fluxRecord.Values["tag"] = "production";
    fluxRecord.Values["min"] = 10.5;
    fluxRecord.Values["max"] = 20.0;
    fluxRecord.Values["avg"] = (Double) 18;
    fluxRecord.Values["_time"] = Instant.FromDateTimeUtc(now);
    
    var poco = _parser.ToPoco<PointWithoutTimestampNameInstant>(fluxRecord);
    
    Assert.AreEqual("production", poco.Tag);
    Assert.AreEqual(10.5, poco.Minimum);
    Assert.AreEqual(20, poco.Maximum);
    Assert.AreEqual(18, poco.Average);
    Assert.AreEqual(Instant.FromDateTimeUtc(now), poco.Timestamp);
}

private class PointWithoutTimestampNameInstant
{
    [Column("tag", IsTag = true)] public string Tag { get; set; }
    [Column("min")] public double Minimum { get; set; }
    [Column("max")] public double Maximum { get; set; }
    [Column("avg")] public Double Average { get; set; }
}   
```

2020-09-08 09:12 UTC, bednar commented on Client.Core/Flux/Internal/FluxResultMapper.cs
>      internal class FluxResultMapper
Please add a test into `FluxResultMapperTest.cs:` to test your changes. Something like:

```csharp
[Test]
public void MapTimestampDifferentName()
{
    var now = DateTime.UtcNow;
    
    var fluxRecord = new FluxRecord(0);
    fluxRecord.Values["tag"] = "production";
    fluxRecord.Values["min"] = 10.5;
    fluxRecord.Values["max"] = 20.0;
    fluxRecord.Values["avg"] = (Double) 18;
    fluxRecord.Values["_time"] = Instant.FromDateTimeUtc(now);
    
    var poco = _parser.ToPoco<PointWithoutTimestampName>(fluxRecord);
    
    Assert.AreEqual("production", poco.Tag);
    Assert.AreEqual(10.5, poco.Minimum);
    Assert.AreEqual(20, poco.Maximum);
    Assert.AreEqual(18, poco.Average);
    Assert.AreEqual(now, poco.Timestamp);
}

private class PointWithoutTimestampName
{
    [Column("tag", IsTag = true)] public string Tag { get; set; }
    [Column("min")] public double Minimum { get; set; }
    [Column("max")] public double Maximum { get; set; }
    [Column("avg")] public Double Average { get; set; }
    [Column(IsTimestamp = true)] public DateTime Timestamp { get; set; }
}
```

2020-09-10 17:59 UTC, ritchiecarroll commented
OK I'll work on these - maybe Friday afternoon before I get a chance.

Thanks,
Ritchie

2020-09-17 03:02 UTC, ritchiecarroll commented
These changes merged into #121

2020-09-17 03:02 UTC, closed without merging