InfluxDB.Client.AspNetCore
influxdata/influxdb-client-csharp pull request #160
Opened 2021-02-15 07:52 UTC by deinok

This adds integration for DependencyInjection and HealthChecks. 
The idea behind is making easy to integrate with AspNetCore but in fact is not really tied to AspNetCore so im not sure about naming it InfluxDB.Client.AspNetCore. Also, the two integrations could be splited in two diferent packages.

PD: The namespaces of the DI related extensions are 'Microsoft.Extensions.DependencyInjection' as it is the recomended.

2021-02-15 15:20 UTC, bednar commented
@deinok Thanks for your PR 👍 We will take a look

2021-02-16 09:27 UTC, bednar requested changes
Thanks again for your PR 👍 

There is a few requirements that should be satisfy before we accept the PR. Could you also add a short README.md that will clarify how to use `InfluxDB.Client.AspNetCore`?

2021-02-16 09:27 UTC, bednar commented on InfluxDB.Client.AspNetCore/InfluxDB.Client.AspNetCore.csproj
> +  </PropertyGroup>
Please add also support for `netstandard2.1` and set `LangVersion` to `8`:

```suggestion
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
    <LangVersion>8</LangVersion>
  </PropertyGroup>
```

2021-02-16 09:27 UTC, bednar commented on InfluxDB.Client.AspNetCore/InfluxDB.Client.AspNetCore.csproj
> +
Please add a detail information about package, something like in `Client.csproj`:

```xml
<Description>...</Description>
<Authors>influxdb-client-csharp Contributors</Authors>
<AssemblyName>InfluxDB.Client.AspNetCore</AssemblyName>
<VersionPrefix>1.16.0</VersionPrefix>
<VersionSuffix>dev</VersionSuffix>

<PackageId>InfluxDB.Client.AspNetCore</PackageId>
<PackageTags>influxdata;timeseries;flux;influxdb</PackageTags>
<PackageIcon>influxdata.jpg</PackageIcon>
<PackageIconUrl>https://raw.githubusercontent.com/influxdata/influxdb-client-csharp/master/Assets/influxdata.jpg</PackageIconUrl>
<PackageProjectUrl>https://github.com/influxdata/influxdb-client-csharp/tree/master/InfluxDB.Client.AspNetCore</PackageProjectUrl>
<PackageLicenseExpression>MIT</PackageLicenseExpression>
<RepositoryUrl>https://github.com/influxdata/influxdb-client-csharp</RepositoryUrl>
<RepositoryType>git</RepositoryType>

<PackageReleaseNotes>https://github.com/influxdata/influxdb-client-csharp/blob/master/CHANGELOG.md</PackageReleaseNotes>
<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
<RootNamespace>InfluxDB.Client.AspNetCore</RootNamespace>

<AssemblyOriginatorKeyFile>../Keys/Key.snk</AssemblyOriginatorKeyFile>
<SignAssembly>true</SignAssembly>
```

2021-02-16 09:27 UTC, bednar commented on InfluxDB.Client.AspNetCore/InfluxDBClientHealthCheck.cs
> +    public class InfluxDBClientHealthCheck : IHealthCheck
Please add tests for `InfluxDBClientHealthCheck`. We want to be sure that everything works between releases.

2021-02-16 09:27 UTC, bednar commented on InfluxDB.Client.AspNetCore/ServiceCollectionExtensions.cs
> +		public static IServiceCollection AddInfluxDBClient(this IServiceCollection serviceCollection, string connectionString, ServiceLifetime serviceLifetime = ServiceLifetime.Scoped)
Please add tests for `AddInfluxDBClient`. We want to be sure that everything works between releases.

2021-02-16 11:29 UTC, deinok commented
@bednar Hey, take a quick look, but I need the connection string for CircleCI to make them pass.

2021-02-16 11:36 UTC, bednar commented
You could extend `AbstractTest` and take InfluxDB URL by: https://github.com/influxdata/influxdb-client-csharp/blob/d1c12e19124a43b6b39514dbb41dffea0fb8e86e/Client.Core.Test/AbstractTest.cs#L60

2021-05-03 11:37 UTC, bednar commented
@deinok, do you want to continue with this PR?

2021-05-05 09:14 UTC, deinok commented
Project got stuck from my enterprise, for now you can close it. If they wake up again I will do it again.

2021-05-05 11:15 UTC, bednar commented
@deinok thanks for info

2021-05-05 11:15 UTC, closed without merging