feat: Updated Dependencies of Client
influxdata/influxdb-client-csharp pull request #175
Opened 2021-03-15 14:24 UTC by deinok

Updates dependencies of Client.csproj

Should none of them have big changes, just performace improvements

2021-03-15 14:43 UTC, bednar requested changes
Thanks for your PR 👍 

Could you please update the `CHANGELOG.md` file?

2021-03-15 17:53 UTC, deinok reviewed
Done

2021-03-16 06:01 UTC, bednar approved these changes

2021-03-16 06:06 UTC, merged

2021-03-16 06:07 UTC, bednar commented
Thanks again for your PR 👍. The PR is merged into master.