feat: Blazor example
influxdata/influxdb-client-csharp pull request #338
Opened 2022-07-19 12:17 UTC by michaelahojna

Closes #

## Proposed Changes

_Briefly describe your proposed changes:_

## Checklist

- [ ] CHANGELOG.md updated
- [ ] Rebased/mergeable
- [ ] A test has been added if appropriate
- [ ] `dotnet test` completes successfully
- [ ] Commit messages are [conventional](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

2022-07-21 05:33 UTC, bednar requested changes

2022-07-21 05:33 UTC, bednar commented on ExampleBlazor/ExampleBlazor.csproj
> +      <PackageReference Include="InfluxDB.Client" Version="4.4.0-dev.6843" />
The package should be referenced via relative path.

```suggestion
      <ProjectReference Include="..\Client\Client.csproj" />
```

2022-07-21 06:25 UTC, bednar requested changes
@michaelahojna, thanks for your PR 👍 

Please reformat sources to required style by: `./Scripts/reformat-code.sh` and create `README.md` with description of the **Blazor example**.

2022-08-31 07:38 UTC, bednar requested changes
Please rebase sources and update `CHANGELOG.md` and also PR description:

![image](https://user-images.githubusercontent.com/455137/187620685-2405aaf3-6faf-4b49-9e9b-5b396500b8e3.png)

2022-08-31 08:13 UTC, rhajek commented
The demo is missing an example how to use LINQ somewhere in `InfluxModel.cs`.

2022-09-01 07:31 UTC, bednar requested changes

2022-09-01 07:31 UTC, bednar commented on Examples/ExampleBlazor/Data/InfluxModel.cs
> +        }
Please use `using` keyword instead explicitly disposing client. Use this behaviour on all places.

```suggestion
        using var influxDbClient = client.GetClient();
        try
        {
            var orgList = await influxDbClient.GetOrganizationsApi().FindOrganizationsAsync(org: client.Org);

            var tmp = orgList.First();
            return (await influxDbClient.GetOrganizationsApi().FindOrganizationsAsync(org: client.Org))
                .First().Id;
        }
        catch (Exception e)
        {
            Debug.WriteLine("Failed to load organization Id." + e);
        }
```

2022-09-01 07:31 UTC, bednar commented on Examples/ExampleBlazor/Data/ClientSettings.cs
> +    }
Use the optional parameter to simplify code:

```suggestion
    public InfluxDBClient GetClient(double timespanSeconds = 10)
    {
        var options = new InfluxDBClientOptions.Builder()
            .Url(Url)
            .AuthenticateToken(Token)
            .TimeOut(TimeSpan.FromSeconds(timespanSeconds))
            .Build();

        return InfluxDBClientFactory.Create(options);
    }
```

2022-09-07 07:36 UTC, bednar approved these changes
LGTM 🚀

2022-09-07 07:36 UTC, merged