Use IEnumerable in WriteApi to elimiate unnecssary memory allocations
influxdata/influxdb-client-csharp pull request #606
Opened 2024-01-17 11:50 UTC by birdalicious

Closes #

## Proposed Changes

Convert the WriteApi from using concrete List as argument as it incurs more memory allocations converting arguments to List, instead use IEnumerable which does not incur any memory allocation

2024-01-18 12:21 UTC, bednar requested changes
@birdalicious thanks for your PR 👍 

Please satisfy our Checklist after that we are be able to approve this PR

<img width="1263" alt="image" src="https://github.com/influxdata/influxdb-client-csharp/assets/455137/5670f1f8-07ea-467f-81c2-9b732b760844">

2024-01-22 09:16 UTC, birdalicious commented
What do I need to run `dotnet test` I've installed all the versions of .NET required but what is the setup up for the influx instances on 8086/9999?

2024-01-22 09:20 UTC, bednar commented
You can start pre-configured InfluxDB instances in a Docker environment using the `/Scripts/influxdb-restart.sh` script.

2024-02-01 16:41 UTC, bednar requested changes

2024-02-01 16:41 UTC, bednar commented on Client/WriteApiAsync.cs
> +            return WriteRecordsAsync(records, precision, bucket, org, cancellationToken);
This causes infinity recursive, please change to:

```suggestion
            return WriteRecordsAsync((IEnumerable<string>)records, precision, bucket, org, cancellationToken);
```

2024-02-01 16:41 UTC, bednar commented on Client/WriteApiAsync.cs
> +            return WritePointsAsync(points, bucket, org, cancellationToken);
This causes infinity recursive, please change to:
```suggestion
            return WritePointsAsync((IEnumerable<PointData>)points, bucket, org, cancellationToken);
```

2024-02-01 16:41 UTC, bednar commented on Client/WriteApiAsync.cs
> +            return WriteMeasurementsAsync(measurements, precision, bucket, org, cancellationToken);
This causes infinity recursive, please change to:
```suggestion
            return WriteMeasurementsAsync((IEnumerable<TM>)measurements, precision, bucket, org, cancellationToken);
```

2024-02-01 16:42 UTC, bednar commented
This PR has been closed because it has not had recent activity. Please reopen if this PR is still important to you and you want to continue with them.

2024-02-01 16:42 UTC, closed without merging